ami:
  enabled: true
  host: 127.0.0.10
  password: admin
  port: '5038'
  username: admin
api:
  base_url: http://192.168.1.37
  enabled: true
  ptt_off_path: /ptt_off
  ptt_on_path: /ptt_offf
radio:
  cm108:
    cos_bit: '0x02'
    device: 0d8c:0012  C-Media Electronics Inc. USB Audio Device
    invert_cos: false
    invert_ptt: false
    pid: '0x0012'
    ptt_bit: '0x01'
    vid: '0x0d8c'
  cos_bit: '1'
  device: 0d8c:0012  C-Media Electronics Inc. USB Audio Device
  invert_cos: false
  invert_ptt: false
  pid: '0x0012'
  ptt_bit: '0'
  serial:
    baudrate: 9600
    invert_cos: false
    invert_ptt: false
    port: COM1 - Communications Port (COM1)
  vid: '0x0d8c'
transmitting:
  pause: 1.0
  pre_roll_delay: 0.5
  ptt_time: 170.0
  rewind: 0.5
